<?php
$fail=0;$count=0;function check($ok,$name){global $fail,$count;$count++;echo ($ok?'PASS':'FAIL')." $name\n";if(!$ok)$fail++;}
require_once dirname(__DIR__).'/services/banking/BankingService.php';
class TestStatement extends PDOStatement { public $row=false; public $rows=[]; public $column=false; public $executed=[]; public function execute(?array $params=null):bool{$this->executed[]=$params;return true;} public function fetch(int $mode=PDO::FETCH_DEFAULT,int $orientation=PDO::FETCH_ORI_NEXT,int $offset=0):mixed{return $this->row;} public function fetchAll(int $mode=PDO::FETCH_DEFAULT,mixed ...$args):array{return $this->rows;} public function fetchColumn(int $column=0):mixed{return $this->column;} }
class TestPDO extends PDO { public $statement; public $prepared=[]; public function __construct(){$this->statement=new TestStatement();} public function query(string $query,?int $fetchMode=null,mixed ...$fetchModeArgs):PDOStatement|false{return $this->statement;} public function prepare(string $query,array $options=[]):PDOStatement|false{$s=new TestStatement();$this->prepared[]=[$query,$s];return $s;} public function exec(string $statement):int|false{if(str_contains($statement,'access_token=NULL')){$this->statement->row['access_token']=null;$this->statement->row['access_expires_at']=null;}return 1;} }
class ImportPDO extends PDO { public $pendingIds=[]; public $existingId=false; public $collisionId=false; public $rule=false; public $queries=[]; public function __construct(){} public function prepare(string $query,array $options=[]):PDOStatement|false{$s=new TestStatement();if(str_contains($query,"status='pending'"))$s->rows=$this->pendingIds;elseif(str_contains($query,'id<>'))$s->column=$this->collisionId;elseif(str_contains($query,'SELECT r.suggested'))$s->row=$this->rule;elseif(str_contains($query,'deduplication_key=?'))$s->column=$this->existingId;$this->queries[]=$query;return $s;} }
class DummyProvider extends MockBankingProvider {}
$base=['bookingDate'=>'2026-09-17','transactionAmount'=>['amount'=>'-12.50','currency'=>'EUR'],'remittanceInformationUnstructured'=>'TEST'];
check(BankingService::transactionKey(1,$base)===BankingService::transactionKey(1,$base),'empreinte stable sans identifiant');
$with=$base;$with['transactionId']='abc';$changed=$with;$changed['bookingDate']='2026-09-18';check(BankingService::transactionKey(1,$with)===BankingService::transactionKey(1,$changed),'identifiant fournisseur prioritaire');
check(BankingService::transactionLabel(['remittanceInformationUnstructuredArray'=>['CB','DECATHLON']])==='CB DECATHLON','libellé tolérant');
$mock=new MockBankingProvider();check(count($mock->requisition('x')['accounts'])===2,'plusieurs comptes');$tx=$mock->transactions('mock-account-1');check(count($tx['transactions']['booked'])===2&&count($tx['transactions']['pending'])===1,'booked et pending');
$institutions=$mock->institutions();check(stripos($institutions[0]['name'],'Agricole')!==false,'institution Crédit Agricole fictive');
check((new GoCardlessException('expired',401))->isConsentError(),'consentement expiré');
$pdo=new TestPDO();$transport=function($method,$url,$body){return ['status'=>200,'body'=>json_encode(['access'=>'access-test','access_expires'=>3600,'refresh'=>'refresh-test','refresh_expires'=>7200])];};
$client=new GoCardlessClient($pdo,'secret-id','secret-key',$transport);check($client->getAccessToken()==='access-test','création du token');
$refreshPdo=new TestPDO();$refreshPdo->statement->row=['access_token'=>'old','access_expires_at'=>'2000-01-01 00:00:00','refresh_token'=>'refresh-old','refresh_expires_at'=>'2999-01-01 00:00:00'];$refreshCalled=false;$refreshTransport=function($method,$url,$body)use(&$refreshCalled){$refreshCalled=str_ends_with($url,'/token/refresh/')&&$body['refresh']==='refresh-old';return ['status'=>200,'body'=>json_encode(['access'=>'access-new','access_expires'=>3600])];};check((new GoCardlessClient($refreshPdo,'id','key',$refreshTransport))->getAccessToken()==='access-new'&&$refreshCalled,'expiration et renouvellement token');
check(($refreshPdo->prepared[0][1]->executed[0][3]??null)==='2999-01-01 00:00:00','refresh conserve expiration existante');
$missing=false;try{(new GoCardlessClient(new TestPDO(),'','',fn()=>[]))->getAccessToken();}catch(GoCardlessException $e){$missing=true;}check($missing,'absence de secrets');
$errorTransport=function(){return ['status'=>503,'body'=>json_encode(['detail'=>'indisponible'])];};$thrown=false;try{(new GoCardlessClient(new TestPDO(),'id','key',$errorTransport))->getAccessToken();}catch(GoCardlessException $e){$thrown=$e->status()===503;}check($thrown,'erreur API token');
$retryPdo=new TestPDO();$retryPdo->statement->row=['access_token'=>'stale','access_expires_at'=>'2999-01-01 00:00:00','refresh_token'=>'refresh-ok','refresh_expires_at'=>'2999-01-01 00:00:00'];$accountCalls=0;$retryTransport=function($method,$url,$body)use(&$accountCalls){if(str_ends_with($url,'/token/refresh/'))return ['status'=>200,'body'=>json_encode(['access'=>'fresh','access_expires'=>3600])];$accountCalls++;return $accountCalls===1?['status'=>401,'body'=>'{}']:['status'=>200,'body'=>json_encode(['account'=>[]])];};$retryResult=(new GoCardlessClient($retryPdo,'id','key',$retryTransport))->getAccountDetails('a');check($accountCalls===2&&isset($retryResult['account']),'401 invalide token et rejoue une seule fois');
check(!BankingService::validCallbackState(hash('sha256','correct'),date('Y-m-d H:i:s',time()+60),'incorrect'),'callback state invalide');
check(BankingService::validCallbackState(hash('sha256','correct'),date('Y-m-d H:i:s',time()+60),'correct'),'callback state valide');
check(BankingService::requisitionOutcome(['status'=>'LN','accounts'=>['a','b']])==='linked','requisition liée');
check(BankingService::requisitionOutcome(['status'=>'EX'])==='expired'&&BankingService::requisitionOutcome(['status'=>'RJ'])==='rejected'&&BankingService::requisitionOutcome(['status'=>'CR'])==='pending','statuts requisition invalides ou en attente');
check(BankingService::canManageBanking(['role'=>'super_admin'])&&!BankingService::canManageBanking(['role'=>'coach'])&&!BankingService::canManageBanking(null),'contrôle accès bancaire');
$datePdo=new TestPDO();$datePdo->statement->row=['access_token'=>'cached','access_expires_at'=>'2999-01-01 00:00:00'];$calledUrl='';$dateTransport=function($method,$url)use(&$calledUrl){$calledUrl=$url;return ['status'=>200,'body'=>json_encode(['transactions'=>[]])];};(new GoCardlessClient($datePdo,'id','key',$dateTransport))->getAccountTransactions('acc','2026-06-01','2026-06-30');check(str_contains($calledUrl,'date_from=2026-06-01')&&str_contains($calledUrl,'date_to=2026-06-30'),'fenêtre de dates transactions');
$importPdo=new ImportPDO();$service=new BankingService($importPdo,new DummyProvider());$method=new ReflectionMethod(BankingService::class,'upsertTransaction');$method->setAccessible(true);$sample=['transactionId'=>'tx-1','bookingDate'=>'2026-09-17','valueDate'=>'2026-09-17','transactionAmount'=>['amount'=>'10.00','currency'=>'EUR'],'remittanceInformationUnstructured'=>'COTISATION'];
check($method->invoke($service,1,'pending',$sample)===true,'import nouvelle transaction');$importPdo->existingId=22;check($method->invoke($service,1,'pending',$sample)===false,'zéro nouveauté et pas de doublon');
$importPdo->existingId=false;$importPdo->pendingIds=[10];check($method->invoke($service,1,'booked',$sample)===false&&count(array_filter($importPdo->queries,fn($q)=>str_contains($q,"status='booked'")))>0,'pending vers booked candidat unique');
$before=count($importPdo->queries);$importPdo->pendingIds=[10,11];check($method->invoke($service,1,'booked',$sample)===true&&count(array_filter(array_slice($importPdo->queries,$before),fn($q)=>str_starts_with($q,'DELETE FROM bank_transactions')))===0,'pending ambigu non supprimé');
$invalid=false;try{$bad=$sample;$bad['transactionAmount']['amount']='abc';$method->invoke($service,1,'booked',$bad);}catch(Throwable $e){$invalid=true;}check($invalid,'montant invalide refusé');
$invalid=false;try{$bad=$sample;$bad['transactionAmount']['currency']='EU';$method->invoke($service,1,'booked',$bad);}catch(Throwable $e){$invalid=true;}check($invalid,'devise invalide refusée');
$rulePdo=new ImportPDO();$rulePdo->existingId=44;$rulePdo->rule=['suggested_category_id'=>7,'suggested_label'=>'Cotisations'];$ruleService=new BankingService($rulePdo,new DummyProvider());$method->invoke($ruleService,1,'booked',$sample);check(count(array_filter($rulePdo->queries,fn($q)=>str_contains($q,"reconciliation_status='suggested'")))===1,'règle suggère catégorie sans écriture définitive');
echo "$count tests, $fail échec(s)\n";exit($fail?1:0);
