<?php
require_banking_access();
$success=$_SESSION['success']??null;$error=$_SESSION['error']??null;unset($_SESSION['success'],$_SESSION['error']);
if(!table_exists('bank_connections')) { header_html('Banque'); echo '<section class="card"><h1>Compte bancaire</h1><div class="alert">Appliquez la migration depuis la page Migrations.</div></section>'; footer_html(); return; }
try{$institutions=banking_service()->creditAgricoleInstitutions();$apiError=null;}catch(Throwable $e){$institutions=[];$apiError=$e->getMessage();}
$stmt=db()->prepare('SELECT c.*,a.id account_id,a.iban,a.name account_name,a.currency,a.current_balance,a.available_balance,a.last_sync_at account_last_sync,a.last_error account_error FROM bank_connections c LEFT JOIN bank_accounts a ON a.bank_connection_id=c.id WHERE c.user_id=? ORDER BY c.created_at DESC,a.id');$stmt->execute([$u['id']]);$accounts=$stmt->fetchAll();
$filters=['q'=>trim((string)($_GET['q']??'')),'from'=>(string)($_GET['from']??''),'to'=>(string)($_GET['to']??''),'flow'=>(string)($_GET['flow']??''),'classified'=>(string)($_GET['classified']??''),'attachment'=>(string)($_GET['attachment']??'')];$p=min(10000,max(1,(int)($_GET['p']??1)));$params=[$u['id']];$where=['c.user_id=?'];
if($filters['q']!==''){$where[]='(t.clean_label LIKE ? OR t.creditor_name LIKE ? OR t.debtor_name LIKE ?)';$like='%'.$filters['q'].'%';array_push($params,$like,$like,$like);}if(preg_match('/^\d{4}-\d{2}-\d{2}$/',$filters['from'])){$where[]='COALESCE(t.booking_date,t.value_date)>=?';$params[]=$filters['from'];}if(preg_match('/^\d{4}-\d{2}-\d{2}$/',$filters['to'])){$where[]='COALESCE(t.booking_date,t.value_date)<=?';$params[]=$filters['to'];}if($filters['flow']==='in')$where[]='t.amount>0';if($filters['flow']==='out')$where[]='t.amount<0';if($filters['classified']==='yes')$where[]="t.reconciliation_status<>'unclassified'";if($filters['classified']==='no')$where[]="t.reconciliation_status='unclassified'";if($filters['attachment']==='yes')$where[]='t.attachment_id IS NOT NULL';if($filters['attachment']==='no')$where[]='t.attachment_id IS NULL';
$base=' FROM bank_transactions t JOIN bank_accounts a ON a.id=t.bank_account_id JOIN bank_connections c ON c.id=a.bank_connection_id WHERE '.implode(' AND ',$where);$count=db()->prepare('SELECT COUNT(*)'.$base);$count->execute($params);$total=(int)$count->fetchColumn();$per=25;$pages=max(1,(int)ceil($total/$per));$p=min($p,$pages);$query=db()->prepare('SELECT t.*,a.name account_name'.$base.' ORDER BY COALESCE(t.booking_date,t.value_date) DESC,t.id DESC LIMIT '.$per.' OFFSET '.(($p-1)*$per));$query->execute($params);$transactions=$query->fetchAll();
header_html('Comptabilité · Banque');
?>
<?php if($success):?><div class="success-alert"><?=e($success)?></div><?php endif;?><?php if($error||$apiError):?><div class="alert"><?=e($error?:$apiError)?></div><?php endif;?>
<div class="toolbar"><div><h1>Compte bancaire</h1><p class="muted-text">Import automatique pour votre comptabilité.</p></div></div>
<?php $hasActive=false;foreach($accounts as $candidate)if($candidate['enabled']&&in_array($candidate['status'],['pending','linked'],true))$hasActive=true;if(!$hasActive):?><section class="card"><h2><?=$accounts?'Reconnecter':'Connecter'?> ma banque</h2><form method="post" class="form-grid"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="action" value="bank_connect"><div class="field full"><label>Choisir la caisse régionale Crédit Agricole</label><select name="institution_id" required><option value="">Sélectionner…</option><?php foreach($institutions as $i):?><option value="<?=e($i['id'])?>"><?=e($i['name'])?></option><?php endforeach;?></select></div><button class="btn"><?=$accounts?'Reconnecter':'Connecter mon compte bancaire'?></button></form></section><?php endif;?>
<?php foreach($accounts as $a):?><section class="card bank-account-card"><div class="toolbar"><div><h2><?=e($a['institution_name'])?></h2><?php if($a['account_id']):?><p><?=e($a['account_name']?:'Compte bancaire')?> · IBAN : <?=e(mask_iban($a['iban']))?></p><div class="bank-balance"><?=e(format_money($a['current_balance'],$a['currency']?:'EUR'))?></div><small>Dernière synchronisation : <?=e($a['account_last_sync']?:'Jamais')?></small><?php else:?><p>Connexion en attente de finalisation.</p><?php endif;?></div><span class="status-badge"><?=e($a['status'])?></span></div><?php if($a['status']==='expired'):?><div class="alert">Connexion bancaire expirée. Reconnectez votre banque pour reprendre la synchronisation.</div><?php endif;?><?php if($a['account_error']):?><div class="alert"><?=e($a['account_error'])?></div><?php endif;?><div class="actions"><?php if($a['account_id']&&$a['enabled']):?><form method="post"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="action" value="bank_sync"><input type="hidden" name="account_id" value="<?=$a['account_id']?>"><button class="btn">Synchroniser maintenant</button></form><?php endif;?><?php if($a['enabled']):?><form method="post" onsubmit="return confirm('Déconnecter la banque ? Les opérations historiques seront conservées.');"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="action" value="bank_disconnect"><input type="hidden" name="confirm" value="yes"><input type="hidden" name="connection_id" value="<?=$a['id']?>"><button class="btn danger">Déconnecter</button></form><?php endif;?></div></section><?php endforeach;?>
<section class="card"><h2>Opérations</h2><form method="get" class="bank-filters"><input type="hidden" name="page" value="banking"><input name="q" placeholder="Rechercher un libellé" value="<?=e($filters['q'])?>"><input type="date" name="from" value="<?=e($filters['from'])?>"><input type="date" name="to" value="<?=e($filters['to'])?>"><select name="flow"><option value="">Entrées et sorties</option><option value="in" <?=$filters['flow']==='in'?'selected':''?>>Entrées</option><option value="out" <?=$filters['flow']==='out'?'selected':''?>>Sorties</option></select><select name="classified"><option value="">Tout classement</option><option value="no" <?=$filters['classified']==='no'?'selected':''?>>À classer</option><option value="yes" <?=$filters['classified']==='yes'?'selected':''?>>Classées</option></select><select name="attachment"><option value="">Tous justificatifs</option><option value="yes" <?=$filters['attachment']==='yes'?'selected':''?>>Avec justificatif</option><option value="no" <?=$filters['attachment']==='no'?'selected':''?>>Sans justificatif</option></select><button class="btn secondary">Filtrer</button></form><div class="table-scroll"><table class="table"><thead><tr><th>Date</th><th>Libellé</th><th>Montant</th><th>État comptable</th></tr></thead><tbody><?php foreach($transactions as $t):?><tr><td><?=e($t['booking_date']?:$t['value_date'])?><?php if($t['status']==='pending'):?><br><small>En attente</small><?php endif;?></td><td><?=e($t['clean_label'])?></td><td class="money <?=$t['amount']>=0?'positive':'negative'?>"><?=e(($t['amount']>=0?'+':'').format_money($t['amount'],$t['currency']))?></td><td><?=e($t['reconciliation_status']==='unclassified'?'À classer':($t['suggested_label']?:$t['reconciliation_status']))?></td></tr><?php endforeach;?><?php if(!$transactions):?><tr><td colspan="4">Aucune opération.</td></tr><?php endif;?></tbody></table></div><div class="pagination"><?php for($i=max(1,$p-3);$i<=min($pages,$p+3);$i++):$qs=array_merge($_GET,['page'=>'banking','p'=>$i]);?><a class="<?=$i===$p?'active':''?>" href="?<?=e(http_build_query($qs))?>"><?=$i?></a><?php endfor;?></div></section>
<?php footer_html();
