<?php
require_once __DIR__.'/GoCardlessProvider.php'; require_once __DIR__.'/MockBankingProvider.php';
class BankingService {
 private $pdo; private $provider;
 public function __construct(PDO $pdo,BankingProvider $provider){$this->pdo=$pdo;$this->provider=$provider;}
 public static function provider(PDO $pdo): BankingProvider {
  $get=function($key,$default=''){if(function_exists('banking_config'))return banking_config($key,$default);$env=getenv($key);return $env!==false&&$env!==''?$env:(defined($key)?constant($key):$default);};
  $mock=filter_var($get('BANKING_MOCK_MODE',false),FILTER_VALIDATE_BOOLEAN);
  $env=strtolower((string)$get('APP_ENV','production'));
  if($mock){if($env==='production')throw new RuntimeException('Le mode bancaire fictif est interdit en production.');return new MockBankingProvider();}
  $id=(string)$get('GOCARDLESS_SECRET_ID','');$key=(string)$get('GOCARDLESS_SECRET_KEY','');
  return new GoCardlessProvider(new GoCardlessClient($pdo,$id,$key));
 }
 public static function canManageBanking(?array $user):bool { return ($user['role']??null)==='super_admin'; }
 public function creditAgricoleInstitutions():array { return array_values(array_filter($this->provider->institutions(),function($i){return preg_match('/cr[eé]dit\s+agricole|credit\s+agricole|agricole/iu',(string)($i['name']??''));})); }
 public function startConnection(int $userId,string $institutionId,string $institutionName,string $redirect):array {
  if($institutionId===''||$institutionName==='')throw new InvalidArgumentException('Caisse régionale invalide.');
  $state=bin2hex(random_bytes(32));$hash=hash('sha256',$state);$ref='coach-'.$userId.'-'.bin2hex(random_bytes(8));
  $link=$this->provider->createLink($institutionId,$redirect.'&state='.rawurlencode($state),$ref);$requisitionId=trim((string)($link['id']??''));$redirectLink=trim((string)($link['link']??''));
  if($requisitionId===''||$redirectLink==='')throw new GoCardlessException('Réponse de connexion bancaire incomplète.');
  $days=(int)($link['agreement']['access_valid_for_days']??90);$s=$this->pdo->prepare("INSERT INTO bank_connections(user_id,provider,institution_id,institution_name,requisition_id,status,callback_state_hash,callback_state_expires_at,consent_expires_at) VALUES(?,'gocardless',?,?,?,'pending',?,DATE_ADD(NOW(),INTERVAL 20 MINUTE),DATE_ADD(NOW(),INTERVAL ? DAY))");
  try{$s->execute([$userId,$institutionId,$institutionName,$requisitionId,$hash,max(1,$days)]);}catch(Throwable $e){try{$this->provider->revoke($requisitionId);}catch(Throwable $ignored){}throw $e;} return ['connection_id'=>(int)$this->pdo->lastInsertId(),'link'=>$redirectLink];
 }
 public static function validCallbackState(string $expectedHash,?string $expiresAt,string $state,?int $now=null):bool {
  if($expectedHash===''||$state===''||!$expiresAt)return false;
  return hash_equals($expectedHash,hash('sha256',$state)) && strtotime($expiresAt)>($now??time());
 }
 public static function requisitionOutcome(array $requisition):string {
  $status=strtoupper((string)($requisition['status']??''));
  if($status==='LN')return 'linked'; if($status==='EX')return 'expired'; if($status==='RJ')return 'rejected'; return 'pending';
 }
 public function completeConnection(int $userId,string $state):array {
  $stateHash=hash('sha256',$state);$s=$this->pdo->prepare("SELECT * FROM bank_connections WHERE user_id=? AND enabled=1 AND status='pending' AND callback_state_hash=? AND callback_state_expires_at>NOW() LIMIT 1");$s->execute([$userId,$stateHash]);$c=$s->fetch();
  if(!$c||!self::validCallbackState((string)$c['callback_state_hash'],$c['callback_state_expires_at']??null,$state))throw new InvalidArgumentException('Retour bancaire invalide ou expiré.');
  $r=$this->provider->requisition((string)$c['requisition_id']);$outcome=self::requisitionOutcome($r);
  if(in_array($outcome,['expired','rejected'],true)){$this->pdo->prepare("UPDATE bank_connections SET status=?,last_error=? WHERE id=?")->execute([$outcome,$outcome==='expired'?'Consent expired':'Consent rejected',$c['id']]);throw new GoCardlessException($outcome==='expired'?'Autorisation bancaire expirée.':'Autorisation bancaire refusée.',403);}
  if($outcome!=='linked')return ['pending'=>true,'accounts'=>0];
  $accounts=array_values(array_filter($r['accounts']??[],'is_string'));
  if(!$accounts)throw new GoCardlessException('La connexion bancaire liée ne contient aucun compte.');
  $this->pdo->beginTransaction();try{foreach($accounts as $providerAccount){$owned=$this->pdo->prepare('SELECT a.id,c.user_id FROM bank_accounts a JOIN bank_connections c ON c.id=a.bank_connection_id WHERE a.provider_account_id=? FOR UPDATE');$owned->execute([$providerAccount]);$existing=$owned->fetch();if($existing&&(int)$existing['user_id']!==$userId)throw new RuntimeException('Ce compte bancaire appartient déjà à un autre utilisateur.');if($existing){$this->pdo->prepare('UPDATE bank_accounts SET bank_connection_id=?,enabled=1 WHERE id=?')->execute([$c['id'],$existing['id']]);}else{$this->pdo->prepare('INSERT INTO bank_accounts(bank_connection_id,provider_account_id) VALUES(?,?)')->execute([$c['id'],$providerAccount]);}}$this->pdo->prepare("UPDATE bank_connections SET status='linked',callback_state_hash=NULL,callback_state_expires_at=NULL,last_error=NULL WHERE id=?")->execute([$c['id']]);$this->pdo->commit();}catch(Throwable $e){$this->pdo->rollBack();throw $e;}
  return ['pending'=>false,'accounts'=>count($accounts),'connection_id'=>(int)$c['id']];
 }
 public static function transactionLabel(array $t):string { foreach(['remittanceInformationUnstructured','remittanceInformationUnstructuredArray','additionalInformation','merchantCategoryCode'] as $k){if(!empty($t[$k]))return is_array($t[$k])?implode(' ',array_map('strval',$t[$k])):(string)$t[$k];}return trim((string)($t['creditorName']??$t['debtorName']??'Opération bancaire')); }
 public static function transactionKey(int $accountId,array $t):string { if(!empty($t['transactionId']))return hash('sha256','id|'.$t['transactionId']);$a=$t['transactionAmount']??[];$refs=[];foreach(['internalTransactionId','entryReference','endToEndId','mandateId','checkId'] as $k)if(!empty($t[$k]))$refs[]=$k.'='.$t[$k];return hash('sha256',implode('|',[$accountId,$t['bookingDate']??'',$t['valueDate']??'',$t['bookingDateTime']??'',$t['valueDateTime']??'',number_format((float)($a['amount']??0),2,'.',''),$a['currency']??'',self::transactionLabel($t),$t['creditorName']??'',$t['debtorName']??'',implode(';',$refs)])); }
 public function syncBankAccount(int $accountId):array {
  $s=$this->pdo->prepare("SELECT a.*,c.id connection_id,c.requisition_id,c.enabled connection_enabled FROM bank_accounts a JOIN bank_connections c ON c.id=a.bank_connection_id WHERE a.id=?");$s->execute([$accountId]);$a=$s->fetch();if(!$a||!$a['enabled']||!$a['connection_enabled'])throw new RuntimeException('Compte bancaire inactif.');
  $this->log('info','sync_started','Bank sync started',(int)$a['connection_id'],$accountId);$new=0;$existing=0;
  try{$d=$this->provider->details($a['provider_account_id']);$b=$this->provider->balances($a['provider_account_id']);$from=date('Y-m-d',strtotime($a['last_sync_at']?'-7 days':'-90 days',strtotime($a['last_sync_at']?:'now')));$to=date('Y-m-d');$tx=$this->provider->transactions($a['provider_account_id'],$from,$to);$detail=$d['account']??$d;$current=null;$available=null;$currency=$detail['currency']??null;foreach($b['balances']??[] as $bal){$type=$bal['balanceType']??'';$amt=$bal['balanceAmount']['amount']??null;$currency=$currency?:($bal['balanceAmount']['currency']??null);if(in_array($type,['closingBooked','interimBooked','expected'],true)&&$current===null)$current=$amt;if(in_array($type,['interimAvailable','forwardAvailable'],true)&&$available===null)$available=$amt;}
   $this->pdo->beginTransaction();$this->pdo->prepare("UPDATE bank_accounts SET iban=?,name=?,currency=?,current_balance=?,available_balance=?,last_error=NULL WHERE id=?")->execute([$detail['iban']??null,$detail['name']??$detail['displayName']??null,$currency,$current,$available,$accountId]);
   foreach(['booked','pending'] as $status)foreach(($tx['transactions'][$status]??[]) as $t){$r=$this->upsertTransaction($accountId,$status,$t);$r?$new++:$existing++;}
   $this->pdo->prepare("UPDATE bank_accounts SET last_sync_at=NOW() WHERE id=?")->execute([$accountId]);$this->pdo->prepare("UPDATE bank_connections SET last_sync_at=NOW(),status='linked',last_error=NULL WHERE id=?")->execute([$a['connection_id']]);$this->pdo->commit();
   $this->log('info','sync_completed','Bank sync completed',(int)$a['connection_id'],$accountId,['fetched'=>$new+$existing,'new'=>$new,'existing'=>$existing]);return ['fetched'=>$new+$existing,'new'=>$new,'existing'=>$existing];
  }catch(Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();$expired=$e instanceof GoCardlessException&&$e->isConsentError();$safe=$expired?'Autorisation bancaire expirée.':'Synchronisation bancaire temporairement indisponible.';$this->pdo->prepare("UPDATE bank_accounts SET last_error=? WHERE id=?")->execute([$safe,$accountId]);if($expired)$this->pdo->prepare("UPDATE bank_connections SET status='expired',last_error=? WHERE id=?")->execute([$safe,$a['connection_id']]);else $this->pdo->prepare("UPDATE bank_connections SET last_error=? WHERE id=?")->execute([$safe,$a['connection_id']]);$this->log('error',$expired?'consent_expired':'sync_failed',$expired?'Consent expired':'Bank synchronization failed',(int)$a['connection_id'],$accountId,['error_class'=>get_class($e)]);throw new RuntimeException($safe,0,$e);}
 }
 private function upsertTransaction(int $accountId,string $status,array $t):bool {
  $amount=$t['transactionAmount']??[];$numeric=$amount['amount']??null;$currency=strtoupper((string)($amount['currency']??''));if(!is_numeric($numeric)||!preg_match('/^[A-Z]{3}$/',$currency))throw new UnexpectedValueException('Transaction bancaire partielle ignorée.');$providerId=isset($t['transactionId'])?(string)$t['transactionId']:null;$key=self::transactionKey($accountId,$t);$label=self::transactionLabel($t);$raw=json_encode($t,JSON_UNESCAPED_UNICODE|JSON_INVALID_UTF8_SUBSTITUTE|JSON_THROW_ON_ERROR);
  if($status==='booked'){$secondary=$this->pdo->prepare("SELECT id FROM bank_transactions WHERE bank_account_id=? AND status='pending' AND amount=? AND currency=? AND (value_date=? OR booking_date=?) AND clean_label=? ORDER BY id LIMIT 2");$date=$t['valueDate']??$t['bookingDate']??null;$secondary->execute([$accountId,$numeric,$currency,$date,$date,substr(trim($label),0,500)]);$candidateIds=$secondary->fetchAll(PDO::FETCH_COLUMN);if(count($candidateIds)===1){$pendingId=$candidateIds[0];$booked=$this->pdo->prepare("SELECT id FROM bank_transactions WHERE bank_account_id=? AND deduplication_key=? AND id<>? LIMIT 1");$booked->execute([$accountId,$key,$pendingId]);$bookedId=$booked->fetchColumn();if($bookedId)return false;$this->pdo->prepare("UPDATE bank_transactions SET provider_transaction_id=?,deduplication_key=?,booking_date=?,value_date=?,amount=?,currency=?,raw_label=?,clean_label=?,creditor_name=?,debtor_name=?,status='booked',raw_data=?,updated_at=NOW() WHERE id=?")->execute([$providerId,$key,$t['bookingDate']??null,$t['valueDate']??null,$numeric,$currency,$label,substr(trim($label),0,500),$t['creditorName']??null,$t['debtorName']??null,$raw,$pendingId]);$this->applyRules($accountId,(int)$pendingId,$label);return false;}}
  $check=$this->pdo->prepare("SELECT id FROM bank_transactions WHERE bank_account_id=? AND deduplication_key=?");$check->execute([$accountId,$key]);$exists=(bool)$check->fetchColumn();
  $sql="INSERT INTO bank_transactions(bank_account_id,provider,provider_transaction_id,deduplication_key,booking_date,value_date,amount,currency,raw_label,clean_label,creditor_name,debtor_name,status,raw_data) VALUES(?,'gocardless',?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE booking_date=VALUES(booking_date),value_date=VALUES(value_date),amount=VALUES(amount),currency=VALUES(currency),raw_label=VALUES(raw_label),clean_label=VALUES(clean_label),creditor_name=VALUES(creditor_name),debtor_name=VALUES(debtor_name),status=VALUES(status),raw_data=VALUES(raw_data),updated_at=NOW()";
  $this->pdo->prepare($sql)->execute([$accountId,$providerId,$key,$t['bookingDate']??null,$t['valueDate']??null,$numeric,$currency,$label,substr(trim($label),0,500),$t['creditorName']??null,$t['debtorName']??null,$status,$raw]);$find=$this->pdo->prepare('SELECT id FROM bank_transactions WHERE bank_account_id=? AND deduplication_key=?');$find->execute([$accountId,$key]);$transactionId=(int)$find->fetchColumn();if($transactionId)$this->applyRules($accountId,$transactionId,$label);return !$exists;
 }
 private function applyRules(int $accountId,int $transactionId,string $label):void{$s=$this->pdo->prepare("SELECT r.suggested_category_id,r.suggested_label FROM bank_rules r JOIN bank_accounts a ON a.id=? JOIN bank_connections c ON c.id=a.bank_connection_id WHERE r.user_id=c.user_id AND r.enabled=1 AND r.match_type='label_contains' AND ? LIKE CONCAT('%',r.match_value,'%') ORDER BY r.id LIMIT 1");$s->execute([$accountId,$label]);$rule=$s->fetch();if(!$rule)return;$this->pdo->prepare("UPDATE bank_transactions SET category_id=?,suggested_label=?,reconciliation_status='suggested' WHERE id=? AND reconciliation_status='unclassified'")->execute([$rule['suggested_category_id']??null,$rule['suggested_label']??null,$transactionId]);}
 public function syncAllBankAccounts():array{$ids=$this->pdo->query("SELECT a.id FROM bank_accounts a JOIN bank_connections c ON c.id=a.bank_connection_id WHERE a.enabled=1 AND c.enabled=1 AND c.status='linked'")->fetchAll(PDO::FETCH_COLUMN);$out=['accounts'=>count($ids),'success'=>0,'failed'=>0];foreach($ids as $id){try{$this->syncBankAccount((int)$id);$out['success']++;}catch(Throwable $e){$out['failed']++;}}return $out;}
 public function disconnect(int $connectionId,int $userId):void{$s=$this->pdo->prepare("SELECT requisition_id FROM bank_connections WHERE id=? AND user_id=?");$s->execute([$connectionId,$userId]);$r=$s->fetch();if(!$r)throw new RuntimeException('Connexion introuvable.');try{if($r['requisition_id'])$this->provider->revoke($r['requisition_id']);}catch(Throwable $e){$this->log('warning','revoke_failed','Remote revocation failed',$connectionId,null,['error_class'=>get_class($e)]);}$this->pdo->beginTransaction();try{$this->pdo->prepare("UPDATE bank_connections SET enabled=0,status='disconnected',last_error=NULL WHERE id=?")->execute([$connectionId]);$this->pdo->prepare("UPDATE bank_accounts SET enabled=0 WHERE bank_connection_id=?")->execute([$connectionId]);$this->pdo->commit();}catch(Throwable $e){$this->pdo->rollBack();throw $e;}}
 private function log(string $level,string $event,string $message,?int $c=null,?int $a=null,array $ctx=[]):void{$clean=array_diff_key($ctx,array_flip(['access','refresh','secret_id','secret_key','iban','raw_data']));$s=$this->pdo->prepare("INSERT INTO bank_sync_logs(bank_connection_id,bank_account_id,level,event,message,context) VALUES(?,?,?,?,?,?)");$s->execute([$c,$a,$level,$event,$message,$clean?json_encode($clean):null]);error_log('[banking] '.$event.' '.$message);}
}
